"""
FastAPI request/response schemas.
"""

from typing import Any

from pydantic import BaseModel, Field


class AnalyzeResponse(BaseModel):
    studentId: str = Field(..., description="Student identifier")
    confused: bool = Field(..., description="Whether the student seems confused")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Top FER confidence")
    emotion: str = Field(..., description="Top FER emotion label")
    gptReason: str = Field(..., alias="gpt_reason", description="Reason generated by GPT")
    signalType: str = Field(..., alias="signal_type", description="Detected understanding decline signal type")
    signalSubtype: str = Field(..., alias="signal_subtype", description="Detected understanding decline signal subtype")
    signalLabel: str = Field(..., alias="signal_label", description="Display label for the detected signal")
    faceFeatures: dict[str, Any] = Field(..., alias="face_features", description="FER and MediaPipe features")

    class Config:
        populate_by_name = True


class SummarizeRequest(BaseModel):
    audioText: str = Field(..., description="Lecture transcript text")


class CoachingSignalItem(BaseModel):
    signalType: str
    label: str
    count: int


class CoachingRecentAlertItem(BaseModel):
    classId: str
    capturedAt: str
    topic: str | None = ""
    reason: str | None = ""
    confusionPercent: int


class CoachingRequest(BaseModel):
    date: str
    curriculum: str | None = ""
    classId: str | None = ""
    classIds: list[str] = Field(default_factory=list)
    participantCount: int = 0
    alertCount: int = 0
    avgConfusionPercent: int = 0
    topKeywords: list[str] = Field(default_factory=list)
    topTopics: list[str] = Field(default_factory=list)
    signalBreakdown: list[CoachingSignalItem] = Field(default_factory=list)
    recentAlerts: list[CoachingRecentAlertItem] = Field(default_factory=list)


class SummarizeResponse(BaseModel):
    summary: str = Field(..., description="Summary generated by GPT")
    recommendedConcept: str = Field(
        ...,
        description="Concept the instructor may want to additionally explain to students",
    )
    keywords: list[str] = Field(
        default_factory=list,
        description="Up to three concise keywords extracted from the lecture",
    )


class ErrorResponse(BaseModel):
    detail: str


class CoachingResponse(BaseModel):
    summary: str
    priorityLevel: str
    coachingTips: list[str] = Field(default_factory=list)
    reExplainTopics: list[str] = Field(default_factory=list)
    studentSignals: list[str] = Field(default_factory=list)
    recommendedActionNow: str
    sampleMentions: list[str] = Field(default_factory=list)
