"""
FastAPI request/response schemas.
"""

from typing import Any

from pydantic import BaseModel, Field


class AnalyzeResponse(BaseModel):
    studentId: str = Field(..., description="Student identifier")
    confused: bool = Field(..., description="Whether the student seems confused")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Top FER confidence")
    emotion: str = Field(..., description="Top FER emotion label")
    gptReason: str = Field(..., alias="gpt_reason", description="Reason generated by GPT")
    faceFeatures: dict[str, Any] = Field(..., alias="face_features", description="FER and MediaPipe features")

    class Config:
        populate_by_name = True


class SummarizeRequest(BaseModel):
    audioText: str = Field(..., description="Lecture transcript text")


class SummarizeResponse(BaseModel):
    summary: str = Field(..., description="Summary generated by GPT")


class ErrorResponse(BaseModel):
    detail: str
