"""
FastAPI request/response schemas.
"""

from typing import Any

from pydantic import BaseModel, Field


class AnalyzeResponse(BaseModel):
    studentId: str = Field(..., description="Student identifier")
    confused: bool = Field(..., description="Whether the student seems confused")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Top FER confidence")
    emotion: str = Field(..., description="Top FER emotion label")
    gptReason: str = Field(..., alias="gpt_reason", description="Reason generated by GPT")
    signalType: str = Field(..., alias="signal_type", description="Detected understanding decline signal type")
    signalSubtype: str = Field(..., alias="signal_subtype", description="Detected understanding decline signal subtype")
    signalLabel: str = Field(..., alias="signal_label", description="Display label for the detected signal")
    faceFeatures: dict[str, Any] = Field(..., alias="face_features", description="FER and MediaPipe features")

    class Config:
        populate_by_name = True


class SummarizeRequest(BaseModel):
    audioText: str = Field(..., description="Lecture transcript text")


class SummarizeResponse(BaseModel):
    summary: str = Field(..., description="Summary generated by GPT")
    recommendedConcept: str = Field(
        ...,
        description="Concept the instructor may want to additionally explain to students",
    )
    keywords: list[str] = Field(
        default_factory=list,
        description="Up to three concise keywords extracted from the lecture",
    )


class ErrorResponse(BaseModel):
    detail: str
